CREATE DATABASE IF NOT EXISTS flash_cards;

USE flash_cards;

CREATE TABLE IF NOT EXISTS decks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  difficulty INT CHECK (difficulty BETWEEN 1 AND 4),
  info VARCHAR(255) NOT NULL,
  num_cards INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS cards (
  id INT AUTO_INCREMENT PRIMARY KEY,
  word VARCHAR(255) NOT NULL,
  answer VARCHAR(255) NOT NULL,
  info VARCHAR(255) NOT NULL
  deck_id
  FOREING KEY (deck_id) REFERENCES decks(id) ON DELETE CASCADE
);